default: &default
  adapter: postgresql
  encoding: unicode
  user: tiago
  password: 12345678
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  user: tiago
  password: 12345678
  pool: 5
  database: datagrid_development_a

test:
  adapter: postgresql
  encoding: unicode
  user: tiago
  password: 12345678
  pool: 5
  database: datagrid_test_a

production:
  adapter: postgresql
  database: datagrid_production
  pool: 5
  timeout: 5000
